name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ github.run_number }}-ci
    - name: Add Nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/bridgefield/index.json -n github -u bridgefield -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Push
      run: dotnet nuget push **/*.nupkg -s github
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: unit test results
        path: '**/test-results.trx'
        reporter: dotnet-trx    
    - name: notify successful execution
      uses: actions/github-script@v6
      id: event-script
      with:
        result-encoding: string
        script: |
          await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: "ci-successful",
            client_payload: { sha: context.sha, ref_name: context.ref.replace("refs/heads/", "") }
          }).then(console.log).catch(console.error);
